import { strFromU8, strToU8, unzipSync, zipSync, type Zippable } from "fflate";
import { cleanText, inspectText, type CleanOptions, type TextInspectReport } from "./clean-text";

// Vercel caps both request and response payloads at 4.5 MB. Keep room for
// multipart boundaries and response headers in the hosted adaptation.
export const MAX_FILE_BYTES = 3 * 1024 * 1024;
const MAX_ARCHIVE_ENTRIES = 2_000;
const MAX_UNCOMPRESSED_BYTES = 32 * 1024 * 1024;

export type SupportedFormat =
  | "text"
  | "markdown"
  | "html"
  | "svg"
  | "pdf"
  | "docx"
  | "odt"
  | "png"
  | "jpeg";

export type FileInspection = {
  kind: "text" | "image" | "container";
  format: SupportedFormat;
  hasC2pa: boolean;
  hasAiMetadata: boolean;
  findings: string[];
  text?: TextInspectReport;
  notes: string[];
};

export type FileCleanResult = {
  format: SupportedFormat;
  outputName: string;
  bytes: Uint8Array;
  bytesIn: number;
  bytesOut: number;
  actions: string[];
  before: FileInspection;
  after: FileInspection;
};

const PNG_SIGNATURE = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg"]);
const CONTAINER_EXTENSIONS = new Set([".svg", ".pdf", ".docx", ".odt", ".html", ".htm", ".md", ".markdown", ".mdx"]);
const TEXT_EXTENSIONS = new Set([".txt", ".text", ".css", ".js", ".ts", ".tsx", ".jsx", ".py", ".rs", ".go", ".json", ".yaml", ".yml", ".toml", ".csv"]);
const AI_FRONTMATTER_KEYS = new Set([
  "generator", "ai", "ai_generated", "ai-generated", "claude", "anthropic", "openai", "gemini", "synthid",
  "c2pa", "content_credentials", "contentcredentials", "provenance", "digital_source_type", "digitalsourcetype",
  "created_with", "createdwith", "model", "llm",
]);
const AI_META_PATTERN = /generator|ai[-_ ]?generated|claude|anthropic|openai|gemini|synthid|c2pa|content.?credential|provenance|digital.?source|aigc/i;
const AI_MARKERS = [
  "c2pa", "jumb", "contentcredentials", "contentauth", "digitalSourceType", "trainedAlgorithmicMedia",
  "compositeWithTrainedAlgorithmicMedia", "algorithmicMedia", "AIGC", "AI generated", "Generated by", "Claude",
  "Anthropic", "OpenAI", "SynthID", "dcterms:provenance",
];
const C2PA_MARKERS = ["c2pa", "jumb", "contentcredentials", "contentauth", "cai:", "http://ns.adobe.com/xmp/InstanceID/"];

function extension(filename: string) {
  const index = filename.lastIndexOf(".");
  return index < 0 ? "" : filename.slice(index).toLowerCase();
}

function startsWith(data: Uint8Array, signature: Uint8Array) {
  return signature.every((value, index) => data[index] === value);
}

function includesAscii(data: Uint8Array, needle: string) {
  return Buffer.from(data).toString("latin1").toLowerCase().includes(needle.toLowerCase());
}

function markerFindings(data: Uint8Array) {
  const body = Buffer.from(data).toString("latin1").toLowerCase();
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  for (const marker of C2PA_MARKERS) {
    if (body.includes(marker.toLowerCase())) {
      hasC2pa = true;
      findings.push(`marker: ${marker}`);
    }
  }
  for (const marker of AI_MARKERS) {
    if (body.includes(marker.toLowerCase())) {
      hasAi = true;
      if (!findings.some((finding) => finding.toLowerCase().endsWith(marker.toLowerCase()))) findings.push(`AI metadata: ${marker}`);
    }
  }
  return { hasC2pa, hasAi: hasAi || hasC2pa, findings: findings.slice(0, 30) };
}

function inspectArchive(data: Uint8Array) {
  let entryCount = 0;
  let uncompressedBytes = 0;
  return unzipSync(data, {
    filter(file) {
      entryCount += 1;
      uncompressedBytes += file.originalSize;
      if (entryCount > MAX_ARCHIVE_ENTRIES || uncompressedBytes > MAX_UNCOMPRESSED_BYTES) throw new Error("Archive is too large when unpacked.");
      return true;
    },
  });
}

export function detectFormat(filename: string, data: Uint8Array): SupportedFormat | null {
  const ext = extension(filename);
  if (startsWith(data, PNG_SIGNATURE)) return "png";
  if (data[0] === 0xff && data[1] === 0xd8) return "jpeg";
  if (Buffer.from(data.subarray(0, 5)).toString("latin1").startsWith("%PDF")) return "pdf";
  if (data[0] === 0x50 && data[1] === 0x4b) {
    const archive = inspectArchive(data);
    if (archive["word/document.xml"]) return "docx";
    if (archive["content.xml"] && archive["meta.xml"]) return "odt";
  }
  if (ext === ".svg") return "svg";
  if (ext === ".html" || ext === ".htm") return "html";
  if (ext === ".md" || ext === ".markdown" || ext === ".mdx") return "markdown";
  if (ext === ".docx") return "docx";
  if (ext === ".odt") return "odt";
  if (IMAGE_EXTENSIONS.has(ext) || CONTAINER_EXTENSIONS.has(ext)) return null;
  if (TEXT_EXTENSIONS.has(ext) || looksLikeText(data)) return "text";
  return null;
}

function looksLikeText(data: Uint8Array) {
  if (data.length === 0) return true;
  const sample = data.subarray(0, Math.min(data.length, 4_096));
  let controls = 0;
  for (const byte of sample) if (byte === 0 || (byte < 9 || (byte > 13 && byte < 32))) controls += 1;
  return controls / sample.length < 0.02;
}

export function inspectFile(filename: string, data: Uint8Array, options: { aggressive?: boolean } = {}): FileInspection {
  const format = detectFormat(filename, data);
  if (!format) throw new Error("Unsupported or mislabeled file. Use PNG, JPEG, SVG, PDF, DOCX, ODT, HTML, Markdown, or a UTF-8 text file.");
  if (format === "png") return inspectPng(data);
  if (format === "jpeg") return inspectJpeg(data);
  if (format === "docx") return inspectDocx(data);
  if (format === "odt") return inspectOdt(data);
  if (format === "pdf") return inspectPdf(data);
  const text = decodeText(data);
  if (format === "markdown") return inspectMarkdown(text, options.aggressive === true);
  if (format === "html") return inspectHtml(text, options.aggressive === true);
  if (format === "svg") return inspectSvg(data);
  const textReport = inspectText(text, { aggressive: options.aggressive });
  return {
    kind: "text", format, hasC2pa: false, hasAiMetadata: false, findings: [], text: textReport,
    notes: ["Plain text receives Layer A Unicode inspection. Statistical marks require the separate Layer B rewrite."],
  };
}

function inspectPng(data: Uint8Array): FileInspection {
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  if (!startsWith(data, PNG_SIGNATURE)) throw new Error("File is not a valid PNG.");
  let position = 8;
  while (position + 12 <= data.length) {
    const length = readU32(data, position);
    const type = Buffer.from(data.subarray(position + 4, position + 8)).toString("latin1");
    const end = position + 12 + length;
    if (end > data.length) throw new Error(`PNG contains a truncated ${type} chunk.`);
    const payload = data.subarray(position + 8, position + 8 + length);
    if (type === "caBX" || type === "juMB" || type.toLowerCase().startsWith("c2")) {
      hasC2pa = true;
      findings.push(`PNG ${type} chunk (possible C2PA/JUMBF container)`);
    }
    if (["tEXt", "zTXt", "iTXt", "eXIf"].includes(type)) {
      const hits = AI_MARKERS.filter((marker) => includesAscii(payload, marker));
      if (hits.length) {
        hasAi = true;
        if (hits.some((hit) => C2PA_MARKERS.includes(hit.toLowerCase()))) hasC2pa = true;
        findings.push(`PNG ${type}: ${hits.slice(0, 8).join(", ")}`);
      }
    }
    position = end;
    if (type === "IEND") break;
  }
  const whole = markerFindings(data);
  if (whole.hasC2pa && !hasC2pa) findings.push(...whole.findings.filter((item) => item.startsWith("marker:")));
  return {
    kind: "image", format: "png", hasC2pa: hasC2pa || whole.hasC2pa, hasAiMetadata: hasAi || hasC2pa || whole.hasAi,
    findings, notes: imageLimitNotes(),
  };
}

function inspectJpeg(data: Uint8Array): FileInspection {
  if (data[0] !== 0xff || data[1] !== 0xd8) throw new Error("File is not a valid JPEG.");
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  let position = 2;
  while (position + 4 <= data.length) {
    if (data[position] !== 0xff) { position += 1; continue; }
    while (position < data.length && data[position] === 0xff) position += 1;
    const marker = data[position++];
    if (marker === 0xda || marker === 0xd9) break;
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd7)) continue;
    if (position + 2 > data.length) break;
    const length = readU16(data, position);
    if (length < 2 || position + length > data.length) throw new Error("JPEG contains a truncated metadata segment.");
    const payload = data.subarray(position + 2, position + length);
    if (marker === 0xeb) {
      hasC2pa = true;
      findings.push("JPEG APP11 segment (common JUMBF/C2PA container)");
    }
    if ([0xe1, 0xe2, 0xeb, 0xed, 0xee].includes(marker)) {
      const hits = AI_MARKERS.filter((needle) => includesAscii(payload, needle));
      if (hits.length) {
        hasAi = true;
        findings.push(`JPEG APP${marker - 0xe0}: ${hits.slice(0, 8).join(", ")}`);
      }
    }
    position += length;
  }
  const whole = markerFindings(data);
  return {
    kind: "image", format: "jpeg", hasC2pa: hasC2pa || whole.hasC2pa, hasAiMetadata: hasAi || hasC2pa || whole.hasAi,
    findings, notes: imageLimitNotes(),
  };
}

function imageLimitNotes() {
  return [
    "The hosted cleaner strips hard-bound container metadata. Pixel-domain SynthID removal and C2PA soft binding are out of scope.",
    "The upstream project offers an optional external reverse-SynthID confidence scorer for research; it detects only and is not bundled here.",
  ];
}

function inspectMarkdown(text: string, aggressive: boolean): FileInspection {
  const findings: string[] = [];
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (match) {
    for (const line of match[1].split(/\r?\n/)) {
      if (!line.trim() || line.trimStart().startsWith("#") || /^[\s-]/.test(line)) continue;
      const keyMatch = line.match(/^([A-Za-z0-9_.-]+)\s*:/);
      if (!keyMatch) continue;
      const key = keyMatch[1];
      const value = line.slice(line.indexOf(":") + 1);
      if (AI_FRONTMATTER_KEYS.has(key.toLowerCase()) || AI_META_PATTERN.test(key) || AI_META_PATTERN.test(value)) findings.push(`Frontmatter key: ${key}`);
    }
  }
  const textReport = inspectText(text, { aggressive });
  const hasC2pa = findings.some((finding) => /c2pa|content.?credential/i.test(finding));
  return {
    kind: "container", format: "markdown", hasC2pa, hasAiMetadata: findings.length > 0, findings, text: textReport,
    notes: ["YAML provenance keys and Layer A Unicode are inspected and cleaned."],
  };
}

function inspectHtml(text: string, aggressive: boolean): FileInspection {
  const findings: string[] = [];
  for (const tag of text.match(/<meta\b[^>]*>/gi) ?? []) if (AI_META_PATTERN.test(tag)) findings.push(`Meta tag: ${tag.slice(0, 120)}`);
  for (const block of text.match(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi) ?? []) {
    if (AI_META_PATTERN.test(block) || /DigitalSourceType|trainedAlgorithmicMedia|SoftwareAgent/i.test(block)) findings.push("JSON-LD provenance-like block");
  }
  for (const attr of text.match(/\bdata-ai[\w-]*\s*=\s*["'][^"']*["']/gi) ?? []) findings.push(`Attribute: ${attr.slice(0, 80)}`);
  const textReport = inspectText(text, { aggressive });
  return {
    kind: "container", format: "html", hasC2pa: findings.some((item) => /c2pa|content.?credential/i.test(item)),
    hasAiMetadata: findings.length > 0, findings, text: textReport,
    notes: ["AI-related meta tags, JSON-LD, data-ai attributes, and Layer A Unicode are inspected and cleaned."],
  };
}

function inspectSvg(data: Uint8Array): FileInspection {
  const text = decodeText(data);
  const markers = markerFindings(data);
  const findings = [...markers.findings];
  if (/<metadata[\s>]/i.test(text)) findings.push("SVG <metadata> block present");
  if (/xmpmeta|rdf:RDF|contentcredentials/i.test(text)) findings.push("XMP/RDF-like content in SVG");
  return {
    kind: "container", format: "svg", hasC2pa: markers.hasC2pa || /c2pa|jumbf/i.test(text),
    hasAiMetadata: markers.hasAi || /<metadata[\s>]|xmpmeta|rdf:RDF/i.test(text), findings,
    notes: ["SVG metadata, XMP/RDF blocks, and provenance comments are inspected and cleaned."],
  };
}

function inspectDocx(data: Uint8Array): FileInspection {
  const archive = inspectArchive(data);
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  for (const [name, bytes] of Object.entries(archive)) {
    const markers = markerFindings(bytes);
    if (markers.hasC2pa || markers.hasAi) {
      hasC2pa ||= markers.hasC2pa;
      hasAi ||= markers.hasAi;
      findings.push(`${name}: ${markers.findings.slice(0, 6).join(", ")}`);
    }
  }
  const customCount = Object.keys(archive).filter((name) => name.startsWith("customXml/")).length;
  if (customCount) findings.push(`customXml parts: ${customCount}`);
  return {
    kind: "container", format: "docx", hasC2pa, hasAiMetadata: hasAi || hasC2pa, findings,
    notes: ["Document properties and custom XML are inspected. The document body is preserved."],
  };
}

function inspectOdt(data: Uint8Array): FileInspection {
  const archive = inspectArchive(data);
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  for (const [name, bytes] of Object.entries(archive)) {
    const markers = markerFindings(bytes);
    if (markers.hasC2pa || markers.hasAi) {
      hasC2pa ||= markers.hasC2pa;
      hasAi ||= markers.hasAi;
      findings.push(`${name}: ${markers.findings.slice(0, 6).join(", ")}`);
    }
  }
  if (archive["meta.xml"] && /generator|claude|openai|anthropic|gemini/i.test(strFromU8(archive["meta.xml"]))) {
    hasAi = true;
    findings.push("meta.xml generator-like fields");
  }
  return {
    kind: "container", format: "odt", hasC2pa, hasAiMetadata: hasAi || hasC2pa, findings,
    notes: ["ODT generator, creator, and non-content provenance parts are inspected and cleaned."],
  };
}

function inspectPdf(data: Uint8Array): FileInspection {
  const markers = markerFindings(data);
  const findings = markers.findings.map((item) => `PDF bytes: ${item}`);
  if (includesAscii(data, "<x:xmpmeta") || includesAscii(data, "application/rdf+xml")) findings.push("XMP packet present");
  return {
    kind: "container", format: "pdf", hasC2pa: markers.hasC2pa, hasAiMetadata: markers.hasAi, findings,
    notes: ["PDF cleaning is a best-effort XMP scrub in this hosted runtime. The upstream CLI prefers exiftool for a more complete pass."],
  };
}

export function cleanFile(filename: string, data: Uint8Array, options: CleanOptions = {}): FileCleanResult {
  if (data.byteLength > MAX_FILE_BYTES) throw new Error(`Files are limited to ${Math.round(MAX_FILE_BYTES / 1024 / 1024)} MB.`);
  const before = inspectFile(filename, data, { aggressive: options.normalizeConfusables });
  let bytes: Uint8Array;
  let actions: string[];
  if (before.format === "png") ({ bytes, actions } = cleanPng(data));
  else if (before.format === "jpeg") ({ bytes, actions } = cleanJpeg(data));
  else if (before.format === "markdown") ({ bytes, actions } = cleanMarkdown(decodeText(data), options));
  else if (before.format === "html") ({ bytes, actions } = cleanHtml(decodeText(data), options));
  else if (before.format === "svg") ({ bytes, actions } = cleanSvg(data));
  else if (before.format === "docx") ({ bytes, actions } = cleanDocx(data));
  else if (before.format === "odt") ({ bytes, actions } = cleanOdt(data));
  else if (before.format === "pdf") ({ bytes, actions } = cleanPdf(data));
  else ({ bytes, actions } = cleanPlainText(decodeText(data), options));
  const outputName = cleanedFilename(filename);
  const after = inspectFile(outputName, bytes, { aggressive: options.normalizeConfusables });
  return { format: before.format, outputName, bytes, bytesIn: data.byteLength, bytesOut: bytes.byteLength, actions, before, after };
}

function cleanPlainText(text: string, options: CleanOptions) {
  const result = cleanText(text, options);
  return {
    bytes: strToU8(result.cleanedText),
    actions: [`Layer A text: removed=${result.stats.removedCount} replaced=${result.stats.replacedCount}`],
  };
}

function cleanPng(data: Uint8Array) {
  const chunks: Uint8Array[] = [data.subarray(0, 8)];
  const actions: string[] = [];
  let position = 8;
  while (position + 12 <= data.length) {
    const length = readU32(data, position);
    const type = Buffer.from(data.subarray(position + 4, position + 8)).toString("latin1");
    const end = position + 12 + length;
    if (end > data.length) throw new Error(`PNG contains a truncated ${type} chunk.`);
    const payload = data.subarray(position + 8, position + 8 + length);
    const drop = ["eXIf", "caBX", "juMB", "tEXt", "zTXt", "iTXt"].includes(type)
      || type.toLowerCase().startsWith("c2")
      || (!new Set(["IHDR", "IDAT", "IEND", "PLTE", "tRNS", "gAMA", "pHYs", "sRGB", "cHRM", "iCCP"]).has(type)
        && C2PA_MARKERS.some((marker) => includesAscii(payload, marker)));
    if (drop) actions.push(`Drop PNG ${type} chunk`);
    else chunks.push(data.subarray(position, end));
    position = end;
    if (type === "IEND") break;
  }
  if (!actions.length) actions.push("No PNG metadata chunks removed");
  return { bytes: concatenate(chunks), actions };
}

function cleanJpeg(data: Uint8Array) {
  const chunks: Uint8Array[] = [data.subarray(0, 2)];
  const actions: string[] = [];
  let position = 2;
  while (position < data.length) {
    const markerStart = position;
    if (data[position] !== 0xff) {
      chunks.push(data.subarray(position));
      actions.push("Preserved remaining image data after an unexpected byte");
      break;
    }
    while (position < data.length && data[position] === 0xff) position += 1;
    if (position >= data.length) break;
    const marker = data[position++];
    if (marker === 0xd9) { chunks.push(data.subarray(markerStart, position)); break; }
    if (marker === 0xda) {
      chunks.push(data.subarray(markerStart));
      actions.push("Preserved entropy-coded image scan");
      break;
    }
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd7)) {
      chunks.push(data.subarray(markerStart, position));
      continue;
    }
    if (position + 2 > data.length) throw new Error("JPEG contains a truncated segment.");
    const length = readU16(data, position);
    const end = position + length;
    if (length < 2 || end > data.length) throw new Error("JPEG contains a truncated metadata segment.");
    const isApp = marker >= 0xe0 && marker <= 0xef;
    const drop = (isApp && marker !== 0xe0) || marker === 0xfe;
    if (drop) actions.push(marker === 0xfe ? "Drop JPEG comment" : `Drop JPEG APP${marker - 0xe0}`);
    else chunks.push(data.subarray(markerStart, end));
    position = end;
  }
  if (!actions.length) actions.push("No JPEG metadata segments removed");
  return { bytes: concatenate(chunks), actions };
}

function cleanMarkdown(text: string, options: CleanOptions) {
  const actions: string[] = [];
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (match) {
    const kept: string[] = [];
    let keepNested = true;
    for (const line of match[1].split(/\r?\n/)) {
      if (/^[\s-]/.test(line) && line.trim()) {
        if (keepNested) kept.push(line);
        continue;
      }
      const keyMatch = line.match(/^([A-Za-z0-9_.-]+)\s*:/);
      if (!keyMatch) { kept.push(line); keepNested = true; continue; }
      const key = keyMatch[1];
      const value = line.slice(line.indexOf(":") + 1);
      const drop = AI_FRONTMATTER_KEYS.has(key.toLowerCase()) || AI_META_PATTERN.test(key) || AI_META_PATTERN.test(value);
      keepNested = !drop;
      if (drop) actions.push(`Drop frontmatter key: ${key}`);
      else kept.push(line);
    }
    const frontmatter = kept.join("\n").replace(/^\n+|\n+$/g, "");
    text = frontmatter ? `---\n${frontmatter}\n---\n${text.slice(match[0].length)}` : text.slice(match[0].length).replace(/^\n+/, "");
    if (!frontmatter) actions.push("Remove empty frontmatter block");
  } else actions.push("No YAML frontmatter");
  const cleaned = cleanText(text, options);
  actions.push(`Layer A text: removed=${cleaned.stats.removedCount} replaced=${cleaned.stats.replacedCount}`);
  return { bytes: strToU8(cleaned.cleanedText), actions };
}

function cleanHtml(text: string, options: CleanOptions) {
  const actions: string[] = [];
  text = text.replace(/<meta\b[^>]*>/gi, (tag) => {
    if (!AI_META_PATTERN.test(tag)) return tag;
    actions.push(`Drop meta tag: ${tag.slice(0, 80)}`);
    return "";
  });
  text = text.replace(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, (block) => {
    if (!AI_META_PATTERN.test(block) && !/DigitalSourceType|trainedAlgorithmicMedia|SoftwareAgent/i.test(block)) return block;
    actions.push("Drop JSON-LD provenance-like script");
    return "";
  });
  let attributeCount = 0;
  text = text.replace(/\sdata-ai[\w-]*\s*=\s*["'][^"']*["']/gi, () => { attributeCount += 1; return ""; });
  if (attributeCount) actions.push(`Drop data-ai attributes x${attributeCount}`);
  const cleaned = cleanText(text, options);
  actions.push(`Layer A text: removed=${cleaned.stats.removedCount} replaced=${cleaned.stats.replacedCount}`);
  return { bytes: strToU8(cleaned.cleanedText), actions };
}

function cleanSvg(data: Uint8Array) {
  let text = decodeText(data);
  const actions: string[] = [];
  text = text.replace(/<metadata\b[^>]*>[\s\S]*?<\/metadata\s*>/gi, () => { actions.push("Drop SVG metadata block"); return ""; });
  text = text.replace(/<x:xmpmeta\b[^>]*>[\s\S]*?<\/x:xmpmeta\s*>/gi, () => { actions.push("Drop SVG XMP block"); return ""; });
  text = text.replace(/<!--[\s\S]*?-->/g, (comment) => {
    if (!AI_META_PATTERN.test(comment)) return comment;
    actions.push("Drop SVG provenance comment");
    return "";
  });
  let attributeCount = 0;
  text = text.replace(/\s(?:inkscape:version|sodipodi:docname|generator)\s*=\s*["'][^"']*["']/gi, () => { attributeCount += 1; return ""; });
  if (attributeCount) actions.push(`Drop SVG generator attributes x${attributeCount}`);
  if (!actions.length) actions.push("No SVG metadata removed");
  return { bytes: strToU8(text), actions };
}

function cleanDocx(data: Uint8Array) {
  const archive = inspectArchive(data);
  const output: Zippable = {};
  const actions: string[] = [];
  for (const [name, raw] of Object.entries(archive)) {
    if (name.startsWith("customXml/")) { actions.push(`Drop part ${name}`); continue; }
    let bytes = raw;
    if (name.startsWith("docProps/")) {
      let text = strFromU8(raw);
      text = text.replace(/(<(?:dc:creator|cp:lastModifiedBy|Application|AppVersion)\b[^>]*>)([\s\S]*?)(<\/(?:dc:creator|cp:lastModifiedBy|Application|AppVersion)>)/gi, (whole, open, value, close) => {
        if (!AI_META_PATTERN.test(value)) return whole;
        actions.push(`Scrub ${name} provenance field`);
        return `${open}${close}`;
      });
      if (name.endsWith("custom.xml") && AI_META_PATTERN.test(text)) { actions.push(`Drop part ${name}`); continue; }
      bytes = strToU8(text);
    }
    if (name === "[Content_Types].xml") {
      let text = strFromU8(bytes);
      let count = 0;
      text = text.replace(/<Override\b[^>]*PartName="\/customXml\/[^"]*"[^>]*\/>/g, () => { count += 1; return ""; });
      if (count) actions.push(`Drop customXml content-type overrides x${count}`);
      bytes = strToU8(text);
    }
    if (name.endsWith(".rels")) {
      let text = strFromU8(bytes);
      let count = 0;
      text = text.replace(/<Relationship\b[^>]*Target="(?:\.\.\/)?customXml\/[^"]*"[^>]*\/>/g, () => { count += 1; return ""; });
      if (count) actions.push(`Drop customXml relationships x${count}`);
      bytes = strToU8(text);
    }
    output[name] = bytes;
  }
  if (!actions.length) actions.push("No DOCX metadata parts removed");
  return { bytes: zipSync(output, { level: 6 }), actions };
}

function cleanOdt(data: Uint8Array) {
  const archive = inspectArchive(data);
  const output: Zippable = {};
  const actions: string[] = [];
  for (const [name, raw] of Object.entries(archive)) {
    let bytes = raw;
    if (name === "meta.xml") {
      let text = strFromU8(raw);
      text = text.replace(/<meta:generator\b[^>]*>[\s\S]*?<\/meta:generator\s*>/gi, () => { actions.push("Drop meta:generator"); return ""; });
      text = text.replace(/<dc:creator\b[^>]*>[\s\S]*?<\/dc:creator\s*>/gi, (block) => {
        if (!AI_META_PATTERN.test(block)) return block;
        actions.push("Drop AI-related creator metadata");
        return "";
      });
      bytes = strToU8(text);
    } else if (!["content.xml", "styles.xml", "mimetype", "META-INF/manifest.xml"].includes(name)) {
      const markers = markerFindings(raw);
      if (markers.hasC2pa || markers.hasAi) { actions.push(`Drop part ${name} (AI/C2PA markers)`); continue; }
    }
    output[name] = name === "mimetype" ? [bytes, { level: 0 }] : bytes;
  }
  if (!actions.length) actions.push("No ODT metadata removed");
  return { bytes: zipSync(output, { level: 6 }), actions };
}

function cleanPdf(data: Uint8Array) {
  const source = Buffer.from(data).toString("latin1");
  let count = 0;
  const cleaned = source.replace(/<\?xpacket begin[\s\S]*?<\?xpacket end[^?]*\?>/gi, (packet) => {
    count += 1;
    return " ".repeat(packet.length);
  });
  const actions = count
    ? [`Blank PDF XMP packet x${count} while preserving byte offsets`, "PDF pass is best-effort in the hosted runtime; exiftool remains preferred for complete stripping"]
    : ["No embedded XMP packet found; PDF copied as-is", "Use the upstream CLI with exiftool for a more complete PDF metadata pass"];
  return { bytes: new Uint8Array(Buffer.from(cleaned, "latin1")), actions };
}

function decodeText(data: Uint8Array) {
  return new TextDecoder("utf-8", { fatal: false }).decode(data);
}

function cleanedFilename(filename: string) {
  const safe = filename.replace(/[^A-Za-z0-9._ -]/g, "_").slice(0, 180) || "cleaned-file";
  const index = safe.lastIndexOf(".");
  return index > 0 ? `${safe.slice(0, index)}.cleaned${safe.slice(index)}` : `${safe}.cleaned.txt`;
}

function readU32(data: Uint8Array, offset: number) {
  return ((data[offset] << 24) | (data[offset + 1] << 16) | (data[offset + 2] << 8) | data[offset + 3]) >>> 0;
}

function readU16(data: Uint8Array, offset: number) {
  return (data[offset] << 8) | data[offset + 1];
}

function concatenate(parts: Uint8Array[]) {
  const output = new Uint8Array(parts.reduce((sum, part) => sum + part.byteLength, 0));
  let offset = 0;
  for (const part of parts) { output.set(part, offset); offset += part.byteLength; }
  return output;
}
